### ISSUE TITLE
Not working ubuntu

### ISSUE THREAD

**Issue by rahuldevanavar91** [ajitsing/apkToJava#3]
I am getting the following error in ubuntu

> dex2jar //apkToJavaTmp/classes.dex -> classes-dex2jar.jar
java.io.FileNotFoundException: File '/apkToJavaTmp/classes.dex' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:56)
	at org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:40)
	at com.googlecode.dex2jar.reader.DexFileReader.<init>(DexFileReader.java:240)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:104)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:174)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:34)
Done!

**Comment by TheElementalOfDestruction** [comment]
Does your file have multiple periods in it? Like "file.name.apk" because I have found that the program is unable to handle that.

**Comment by ajitsing** [comment]
@rahuldevanavar91 If you were trying to debug an apk which was having spaces or dots then that issue is fixed in 1.3.1. Let me know if you are still facing the issue.

**Comment by ajitsing** [comment]
Please retry with the latest version and reopen this issue if you still face the same problem.
